config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users

  root to: "static#index"
  resources :blogs, only: [:index, :show], path: "blog"
  get "tags/:tag", to: "blogs#index", as: :tag

  get "/blog/:year/:month/:slug", to: redirect("/blog/%{slug}")
  resources :legal_pages, only: :show, path: "legal"
end

app/models/blog.rb
class Blog < ApplicationRecord
  include OrderQuery, Taggable
  has_paper_trail

  extend FriendlyId
  friendly_id :title, use: :slugged

  default_scope { order(date: :desc) }
  scope :published, -> { where(published: true) }

  order_query :order_date, [:date, :desc]

  has_attached_file :image, {
    styles: {thumb: "100x100>", main: "800x800#"},
  }.merge(PAPERCLIP_STORAGE_OPTIONS)

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates_presence_of :title, :date, :image, :copy

  rails_admin do
    navigation_label "Blog"

    field :title
    field :date
    field :image
    field :copy, :ck_editor
    field :tags
    field :published
  end

  def self.tagged_with(slug)
    Tag.find_by_slug!(slug).blogs
  end

  def next
    Blog.published.order_date_at(self).next(false)
  end

  def previous
    Blog.published.order_date_at(self).previous(false)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show]

  def index
    if params[:tag]
      @tag = Tag.friendly.find(params[:tag])
      @blogs = Blog.tagged_with(@tag.slug).published.paginate(page: params[:page])
    else
      @blogs = Blog.published.paginate(page: params[:page])
    end
  end

  def show
  end

  private

  def set_blog
    @blog = Blog.friendly.published.find(params[:id])
  end
end

app/views/blogs/_blog.html.erb
<li class="blog__post" style="background-image: url(<%= blog.image.url(:main) %>)">
  <%= link_to blog, class: "blog__link" do %>
    <%= content_tag :h4, blog.title %>
  <% end %>
</li>

app/views/blogs/index.html.erb
<section class="blog-section">
  <div class="wrap">
    <div class="panel__header">
      <div class="panel__header-inner">
        <h1 class="panel__header-title">
          Blog News
        </h1>
      </div>
    </div>

    <div class="blog">
      <ul class="blog__posts">
        <%= render @blogs %>
      </ul>

      <%= will_paginate @blogs %>
    </div>
  </div>
</section>

app/views/blogs/show.html.erb
<section class="blog-section">
  <div class="wrap">
    <div class="blog__header-navigation">
      <div class="blog__header-navigation-inner">
        <%= link_to "Back", blogs_path, class: "blog__back-button" %>
      </div>
    </div>

    <div class="panel__header">
      <div class="panel__header-inner">
        <h1 class="panel__header-title">
          <%= @blog.title %>
        </h1>
      </div>
    </div>

    <div class="blog">
      <p>Posted on <%= @blog.date.strftime("%d %B %Y") %></p>
      <%= raw @blog.copy %>
      <div class="tags">
        <%= render @blog.tags %>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="blog__navigation">
      <%= link_to_if(@blog.previous, "Previous", @blog.previous, class: "blog__navigation-link blog__navigation-link--previous"){} %>
      <%= link_to_if(@blog.next, "Next", @blog.next, class: "blog__navigation-link blog__navigation-link--next"){} %>
    </div>
  </div>
</section>